name: golden-config-test
on:
  workflow_dispatch
jobs:
  golden-config-test-job:
    runs-on: jobset
    container:
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-jobset:latest
      env:
        GCS_PREFIX: gs://axlearn-arc-testing/testing
        ARC_JOBSET_NAME: golden-config-test
        ARC_JOBSET_JSON: /var/arc/cpu-golden-config.json
        JOBSET_DOCKER_IMAGE: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-cpu:python3.10
        JOBSET_HEALTHY_TIMEOUT: 3600
        RESUME_JOBSET: true
        # Optional flags
        # CUSTOM_GIT_ORIGIN: https://github.com/apple/axlearn # Optionally point to another repo
        # CUSTOM_GIT_BRANCH: main # Customize with a different branch
        # JOBSET_MAX_RESTARTS: 1 # Allow restarts in the JobSet. Default = 0 (no restarts)
        # SCHEDULE_TIMEOUT: 600 # Seconds to wait for job to be scheduled. Default = 900
        # POST_SETUP_CMD: # Execute a command after git setup and dependency resolution is complete
    steps:
      - name: Install the Kubernetes Python SDK
        run: uv pip install kubernetes
      - name: Launch the Golden Config test
        run: GH_RUN_ID=${{ github.run_id }} python3 /var/arc/launch_jobset.py
      - name: Delete JobSet if cancelling
        if: cancelled()
        run: python3 /var/arc/cleanup_jobset.py