name: gpu-unit-tests
on:
  workflow_dispatch
jobs:
  gpu-unit-tests-job:
    runs-on: gpu
    container:
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-gpu:python3.12
      env:
        GCS_PREFIX: gs://axlearn-arc-testing/testing
        # Optional flags
        # CUSTOM_GIT_ORIGIN: https://github.com/apple/axlearn # Optionally point to another repo
        CUSTOM_GIT_BRANCH: jax_0.9.1_dev
    steps:
      - name: Persist the run id
        run: echo ${{ github.run_id }} > /var/arc/run_id
      - name: Fetch the target AXLearn origin and branch
        run: /bin/bash /var/arc/git-setup.sh
      - name: Install AXLearn and pytest dependiencies with uv
        run: cd /root && uv pip install .[core,gpu,gcp] pytest pytest-instafail pytest-xdist pytest-csv pytest-timeout
      - name: Create output directories
        run: mkdir -p /home/runner/_work/csv_results
      - name: Run unit tests
        run: /bin/bash /var/arc/gpu-unit-tests.sh && echo "All tests passed successfully"