name: tpu-multislice-training-test
on:
  workflow_dispatch:
  workflow_call:
jobs:
  tpu-multislice-training-test-job:
    runs-on: jobset # Runs on CPU because this schedules a JobSet that's later routed to TPU
    container:
      # image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-jobset-post-cmd-nightly:latest
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-jobset-gcs-update:latest
      env:
        # Required environmental variables for a successful run
        ARC_JOBSET_NAME: arc-tpu-multislice
        ARC_JOBSET_JSON: /var/arc/tpu-multislice.json
        GCS_PREFIX: gs://axlearn-arc-testing/testing
        # JOBSET_DOCKER_IMAGE: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-tpu:python3.12
        JOBSET_DOCKER_IMAGE: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-tpu-py312-jax-nightly:latest
        JOBSET_HEALTHY_TIMEOUT: 900
        ACCELERATOR: v6e_4x4_2
        # Optional flags
        CUSTOM_GIT_ORIGIN: https://github.com/Borklet-Labs/axlearn # Optionally point to another repo
        CUSTOM_GIT_BRANCH: jax_py3.12_nightly
        # CUSTOM_GIT_BRANCH: jax_0.6.2_py3.12 # Customize with a different branch
        # JOBSET_MAX_RESTARTS: 1 # Allow restarts in the JobSet. Default = 0 (no restarts)
        # POST_SETUP_CMD: # Execute a command after git setup and dependency resolution is complete
        POST_SETUP_CMD: pip install -U --pre jax jaxlib libtpu==0.0.30 requests -i https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/ -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
    steps:
      - name: Install the Kubernetes Python SDK
        run: uv pip install kubernetes
      - name: Launch the TPU training job
        id: launch_job
        run: |
          export GITHUB_OUTPUT=$GITHUB_OUTPUT
          GH_RUN_ID=${{ github.run_id }} python3 /var/arc/launch_jobset.py
      - name: Upload the training result to GCS
        if: always()
        env:
          GCS_PREFIX: gs://axlearn-arc-testing/testing
        run: |
          JAX_VER=${{ steps.launch_job.outputs.jax_version }}
          GH_RUN_ID=${{ github.run_id }} JAX_VER="${JAX_VER}" bash /var/arc/upload-result.sh
